### PR TITLE
Fix account creation and recovery in Edge browser

### PR DESCRIPTION
**Pull request by zone117x**
This fixes account creation and recovery when using Edge browser. 
The problem was Edge not supporting the use of crypto APIs within web workers. 
This PR simply does a runtime check for crypto API support in web workers, and falls back to doing the work on the main thread when not supported. 

Fixes 
https://github.com/blockstack/blockstack-browser/issues/1730
https://github.com/blockstack/blockstack-browser/issues/1725
https://github.com/blockstack/blockstack-browser/issues/1698

Does not fix: 
* Some css/positioning issues with placeholder text. 
* Bugs with Edge versions earlier than 44.

### CODE REVIEW

**Comment by zone117x** [comment]
Added @aulneau as reviewer since you may have some input on the cross-browser supported related changes, and since Ken is on vacation.

**Comment by zone117x** [comment]
Something to note - the exception causing this problem was never logged to console, and Edge developer tools were too cumbersome "break on all exceptions" and filter through the hundreds to find this one.
Identifying this bug required enabling trace logging, then putting try/catch/logs around suspicious areas of code.

Anyone with more React experience know how we can get these exceptions to be more prominent, as opposed to just having the GUI glitch out?

**Comment by hstove** [comment]
When I test on Edge, I'm using the Netlify preview, and I can't even get past the step where I enter my desired username. I click continue and nothing happens. This might be related to #1698 

edge browser issue

**Comment by zone117x** [comment]
Dang. I only tested the login to existing account flow. @hstove can you confirm that at least is fixed with this PR?
I'll look into account creation as well.

**Comment by hstove** [comment]
> I only tested the login to existing account flow. @hstove can you confirm that at least is fixed with this PR?

Confirmed, works well.

**Comment by aulneau** [comment]
Just tested this on Edge, works for recovery and new user registration!

**Comment by zone117x** [comment]
@hstove I just tested account creation on Edge and it is working. Only problems I'm seeing are some css positioning issues, and the encryption/decryption process taking much longer in Edge than other browsers. 

Can you re-test?

**Comment by yknl** [comment]
I just tested recovery using the deploy preview on Edge 42.17134 using a 12 word phrase. Clicking the "Sign In" button didn't do anything. The console logs also didn't show any errors.

**Comment by zone117x** [comment]
@yknl Use Edge 44 (should just need to run Windows Update). There are significant problems with the DOM usage in earlier versions that I doubt we will ever fix. I think @hstove looked into some of them and could provide more details.

**Pull request merged**
