### PR TITLE
Selenium tests for account creation and recovery

### PR DESCRIPTION
**Pull request by zone117x**
## PR Summary

* Test suites for account creation, account sign in via key, and sign in via recovery code. 
* Implements a test harness for building out future tests suites using a simple `createTestSuites(...)` call and a series of Mocha test steps. 
* Adds a CircleCI job that runs e2e tests against BrowserStack. The test results will show as another Github Check from CircleCI check in commits. 
* Fixes a React page state bug with account recovery via magic code. There was a race condition with the React state for displaying "Loading..." during recovery code decryption, while at the same time presenting, destroying, then re-presenting the email form DOM. This behavior only looked like a page flicker for the end-user, but for programmatic testing this created several error modes dependent on network and CPU timing and web-browser-specific behaviors. 
* Includes a vscode `launch.json` config that allows proper debugging (breakpoints, variable inspection, stepping, etc..) of e2e test code. 
* Cleanup hardcoded name registrar endpoint, and added ability to override the name registrar from the front-end (i.e. dev console and selenium tests), for the purpose of testing account/ID creation on staging/test servers rather than spamming production. 

## Running Tests

These test can be ran using the web browsers on your local machine or using BrowserStack's environments. The tests can be targeting against any provided hosted browser endpoint as well as a locally built & hosted endpoint. 

Use `npm run test-e2e:localBuild` to build and host the browser locally, then run tests using your local system web browsers.

Use `npm run test-e2e:browserstack` to build and host the browser locally, then run tests against BrowserStack's grid. All major operating systems and browsers are setup and working, including iOS and Android. 

To specify an endpoint and BrowserStack usage, use `npm run test-e2e` with environment variables `E2E_BROWSER_HOST={url|directory}` and `USE_BROWSERSTACK={true|false}`. 

If `E2E_BROWSER_HOST` is set and is not an `http(s)://` url, it is assumed to be a local file system directory, and a local static web server will be spawned and pointed at the directory. 

Use mocha's `--grep` or `--fgrep` options in `mocha.opt` to target specific test suites and/or web browsers / environments. For example: `--grep secret\skey.*iOS-12-iPhone-XS` or `--fgrep firefox`.

#### Using BrowserStack

In order to run tests against BrowserStack, auth credentials must be specified in the environmental variable `BROWSERSTACK_AUTH` with the format `"user:key"`. 

For example `BROWSERSTACK_AUTH="alice1:yUDBktWP1tRdrfq5Lpck"`.

#### Running against the production name registrar

By default, the account creation tests will use the `test-registrar.blockstack.org` name registrar with the `.test-personal.id` domain suffix. This is to avoid spamming `.blockstack.id` with test IDs. 

The production name registrar can be enabled by setting the environment variable `TEST_PRODUCTION_REGISTRAR`.

## Writing new test suites

Use `createTestSuites({test suite description}, ... )` which takes care of initializing a selenium WebDriver for each web browser environment. For example:

```js
const createTestSuites = require('../utils/create-test-suites');

createTestSuites('account recovery via secret key', ({ driver, browserHostUrl }) => {

  step('load initial page', async () => {
    await driver.get(browserHostUrl);
  });

  step('load sign in page', async () => {
    await driver.click(By.xpath('//a[contains(.,"Sign in with an existing ID")]'));
  });

  step('enter secret recovery key', async () => {
    await driver.setText(By.css('textarea[name="recoveryKey"]'), SECRET_RECOVERY_KEY);
    await driver.click(By.css('button[type="submit"]'));
  });

});
```

## Next steps

* [Devops] Setup these tests on internal servers to be ran against our production hosted browser on a daily interval (or something like that).
* Write test suite to go through the authentication flow from a test webapp using blockstack auth.
* Figure out a good way to get the test suites to run in parallel against BrowserStack environments, since it takes several minutes to run through the whole matrix in serial.

### CODE REVIEW

**Comment by yknl** [comment]
Awesome work @zone117x. The tests against BrowserStacks's grid worked perfectly for account creation. There are a few failed tests for account recovery. And it looks like a text input issue. (List of failed targets below) I also had to set an env var for the BrowserStack credentials. Maybe this can go in a testing instruction doc. 

It would also be good to see the instructions for writing new test suites as comments in the test files or as a template in the `test-e2e` directory.

Lastly, I ran into an issue running the tests on my local system installation of Firefox, but I think that's probably due to my Firefox being a really old version. 

Failed tests:
```
account recovery via magic recovery code [Win10-Chrome-71.0]
account recovery via magic recovery code [macOS-10.14-Mojave-Firefox-64.0]
account recovery via magic recovery code [Win10-Firefox-64.0]
account recovery via magic recovery code [Android-9.0-Google-Pixel-3]
account recovery via magic recovery code [Android-6.0-Google-Nexus-6]
account recovery via magic recovery code [Android-8.0-Samsung-Galaxy-S9]
```
Error message
```
Error checking for "Restoring your Blockstack ID" spinner: TimeoutError: Waiting for element to be located By(xpath, //*[contains(text(), "Restoring your Blockstack ID")])
Wait timed out after 3485ms
```
Screenshots of failure:
err
galaxy-s9

**Comment by zone117x** [comment]
👍 on adding instruction docs to the repo - will work on that. 

Glad to see only 1 flaky test failing for you. When running the full test suite there is almost always one or a couple random failures that don't reoccur again very often. It's incredible how flaky selenium is (see the comments in src for all the existing anti-flake workarounds implemented). I'll add a bunch more defensive programming around the `sendKeys` method and hopefully take care of that specific failure.

**Comment by zone117x** [comment]
@yknl A readme has been added to the e2e tests dir.

Those failing tests have been fixed - there was a race condition with the react state for displaying "Loading..." during recovery code decryption while at the same time presenting, destroying, then re-presenting the email form DOM. This behavior had several error modes, dependent on network and CPU timing and webbrowser-specific behaviors, so it took some time to debug and fix.

**Comment by hstove** [comment]
I see that the `Win10` edge environment is commented out. Is that because we need the edge fixes to get merged first?

**Comment by zone117x** [comment]
@hstove Yep thats right, we should be merging the Edge fix PR soon and then I'll enable Win10-Edge on this PR.

**Pull request merged**
