### PR TITLE
Feature/name registration warning

### PR DESCRIPTION
**Pull request by larrysalibra**
This pull request addresses #1090 & #1123.

It displays a warning screen to the user with information about what happens during name registration.
34298135-1da1696e-e757-11e7-9de1-b109d0c71ae4
34298136-20533444-e757-11e7-8d0f-307f41e83a2d

This should have UI component tests but we haven't yet set up our framework for that.

@yknl can you take a look at this when you have a chance?

### CODE REVIEW

**Comment by shea256** [comment]
@larrysalibra Just commented in #1090 about the copy.

**Comment by yknl** [comment]
I agree with @shea256 's comments in #1090. "Hope nobody beats you to it!" seems a little too harsh and lacks context as the title of that modal. Perhaps we should say that name registration requests cannot be guaranteed. There is a small chance that someone may beat you to it.

**Comment by shea256** [comment]
@yknl Yeah and in general I think this copy needs quite a bit of work. We also need continuity of this copy across the modals. Having someone who is just thinking about copy here would be extremely helpful.

**Comment by yknl** [comment]
Proposed copy: @shea256 
registration-disclaimer

**Comment by shea256** [comment]
Very nice work Ken, this is pretty awesome.

A couple of things I was wondering:

1. Should we first mention that registrations are a race or is that clear enough already?
2. Will the user know what "Blockstack PBC" is or should we say no company gets the fee?

If that's the case then it could look something like this:

---

### Name Registration Disclaimer

You're about to create a registration request for myblockstack.id

Please confirm you understand the following:

- Registrations are a race & there's a small chance someone else will win
- Registration requests have a fee regardless of the outcome
- Fees are destroyed on the network and not sent to any company

---

Let me know your thoughts.

**Comment by yknl** [comment]
I think yours is an improvement. I'll make those changes and merge this PR.

**Comment by yknl** [comment]
image

**Comment by shea256** [comment]
Awesome!

**Comment by larrysalibra** [comment]
Great work on this @yknl ! Thanks!

**Pull request merged**
