### PR TITLE
Absolute Path support via Babel resolver

### PR DESCRIPTION
**Pull request by kkomaz**
Closes: https://github.com/blockstack/blockstack-browser/issues/825

- Absolute path import support
- 2 Libraries added: babel-plugin-module-resolver && eslint-import-resolver-babel-module
- babel-plugin-module-resolver is responsible for the proper aliasing
- eslint-import-resolver-babel-module will fix the eslint issues
- Did some testing with several components to make sure nothing was breaking

To add additional aliasing it is as easy as going into the `.babelrc` and adding more keys to the "alias" object.  For example

```
"alias": {
  "js": "./app/js",
  "styles": "./app/styles"
}
```

### CODE REVIEW

**Comment by larrysalibra** [comment]
Thanks @kkomaz - @cwackerfuss can you take a look at this? Here was our earlier discussion about it: https://github.com/blockstack/blockstack-browser/issues/825#issuecomment-331442929

**Comment by aulneau** [comment]
This is great! I actually recently just implemented this here -> https://github.com/blockstack/blockstack-browser/commit/403ea67b697d889c91b5491a565eff29ad00732b without seeing this PR.

I think this would be a great addition! Most of the projects I work on/have worked on use this. Regarding your concerns @larrysalibra, the plugin has 156,038 downloads in the last week, so a lot of people use it and is well tested. 

I'd make the recommendation that we prefix our paths with `@` so there is a clear distinction between internal and external resources. cc @cwackerfuss

**Comment by kkomaz** [comment]
Either way works for me.  This is a pretty old PR from awhile back.  @cwackerfuss

**Comment by cwackerfuss** [comment]
Thanks, sorry about the confusion @kkomaz -- closing this now. @aulneau make sure to reference the issue in a PR once you push.

**Pull request closed without merging**
