### PR TITLE
Merge master to browser webapp

### PR DESCRIPTION
**Pull request by kantai**
This will update browser.blockstack.org to v0.21.6

It also rolls back the changes to the webapp which were tokensale specific and makes this branch match `master`:

```
$ git diff master feature/webapp-match-to-master | wc -l
0
```

### CODE REVIEW

**Comment by kantai** [comment]
One of @yknl or @larrysalibra will have to approve and merge this PR (I don't have write access)

**Comment by larrysalibra** [comment]
Thanks @kantai! I’ll take a look at this today!

**Comment by larrysalibra** [comment]
I also verified that this matches master as well. Looks good to me. I'll merge and deploy.

**Comment by larrysalibra** [comment]
This is deployed at https://browser.blockstack.org and works for me - was able to sign in to blockstack todos and store some todos.

**Pull request merged**
