### PR TITLE
Update BlockPortfolio info

### PR DESCRIPTION
**Pull request by patrickdevivo**
- Replaced the icon image with one without text
- Update name `Blockportfolio` -> `BlockPortfolio`

### CODE REVIEW

**Comment by patrickdevivo** [comment]
@guylepage3 just bumping this again

**Comment by guylepage3** [comment]
Hey @patrickdevivo will have to get to this tomorrow. Our token sale is on at the moment. lots going on. Thanks for your patience. sir. :)

**Comment by patrickdevivo** [comment]
just another bump, @guylepage3

**Comment by guylepage3** [comment]
Thanks for the reminder @patrickdevivo. Will do this now.

**Pull request merged**
