### PR TITLE
Perform smart profile reads and writes, and fix the address generation bug

### PR DESCRIPTION
**Pull request by kantai**
This addresses #1112 #1154 

Mostly, it performs reads _and_ writes of profiles more intelligently -- as described in #1154.
Reads check any of the valid locations (or the zonefile pointer), using the identity address to validate when the correct location is found. Writes go to either the default location, or wherever the zonefile points, and raises an error if the zonefile location cannot be written to.

In order to test this functionality, get your recovery-phrase ready. Wipe-restore your browser -- profiles with zonefile entries (which are writable) should behave normally. Profiles written to old locations _without_ names should be _read_ correctly, and then the writes should go to the new `/hub/<identity-address/profile.json` location.

This PR _does_ not change the behavior of the redux state, just the way that the state is generated, which I'm pretty sure means that we don't need to perform the state-change upgrade. _However_, if users wish to get at their missing addresses, they will need to reset/restore. So I'm not sure of the best strategy there.

### CODE REVIEW

**Comment by yknl** [comment]
Hey @kantai, I ran into the following issue while testing this out:

After saving my index 2 profile, all subsequent addresses seem to be picking up the profile.json of the last address that has a profile.json. 

If I add a profile to my index 3 address, then all subsequent addresses will pick up the profile from index 3.

**Comment by yknl** [comment]
On further testing, it seems to be only happening for adjacent indexes.

**Comment by kantai** [comment]
Thanks for testing @yknl! I'll look into this.

**Comment by kantai** [comment]
I believe this bug came up because I hadn't pushed the merge commit b6d6b790271b8f980921eaeb9e7a5aef87fd57de of `hotfix/address-index-bug` --- the profile read path assumes that no-zonefile profiles for an identity with address `X` of (browser) index `i` come from one of the following locations, given that the 0th address is `A`:

* `{hub}/{X}/profile.json`
* If `i in [0,1]`:  `{hub}/{A}/{i}/profile.json`
* If `i` is odd and `>1`: `{hub}/{A}/{1 + (i divided by 2)}/profile.json`

That logic only works if the browser was reset -- otherwise the location `{hub}/{A}/{1 + (i divided by 2)}/profile.json` should _also_ be a possible location -- we can add that path as well to the possible set if we don't want users to have to reset their browser.

But anyways, the code _should_ have only succeeded in reading a profile for a given identity if the `profile.json` was validly signed by that identity -- do you have any screenshots of the behavior so I can look more into what was going on there?

**Comment by yknl** [comment]
@kantai It looks like this is a separate bug that also exists in develop.

**Comment by yknl** [comment]
@kantai I submitted a fix for the above mentioned bug that I found during testing. If you pull it from develop we can test it out with the changes in this PR.

**Comment by kantai** [comment]
Excellent, thanks @yknl!

Just tested this out and it works for me

**Comment by larrysalibra** [comment]
Taking a look at this now!

**Comment by larrysalibra** [comment]
I'm having trouble with one of the tests timing out:

screen shot 2018-01-24 at 9 59 22 pm

I suspect it's because the test doesn't have mocks for the profile reads so they are hitting the network.

**Comment by larrysalibra** [comment]
@kantai added a commit to mock those requests and configured `nock` to throw an error if there's unmocked network access.

**Comment by kantai** [comment]
Awesome! Thanks for the reviews @yknl and @larrysalibra (and thanks for fixing the mock URLs I was missing!)

Merging to develop now.

**Pull request merged**
