### PR TITLE
Support for building Windows app on Windows

### PR DESCRIPTION
**Pull request by zone117x**
Ported the shell build scripts and vsts config over to package.json scripts (similar setup to the macOS build scripts).

Building the Windows app and .msi now only requires running `npm run win32`

@kantai This is largely an additive PR, only couple minor changes to `BlockstackBrowser.csproj` and `BlockstackSetup.wixproj` to fix:
1. Long file paths when repo is not installed close to the drive root (ex: `C:\Users\matt\Documents\Source\Blah\Projects\blockstack-browser` vs `C:\blockstack-browser`
2. msbuild/batch path evaluation when deep git-bash integration into cmd.exe is not installed. 

Should only need to double check that the current msi producing CI works without issue.

### CODE REVIEW

**Comment by kantai** [comment]
Cool, thanks @zone117x, taking a crack at updating the CI to use this now.

**Comment by kantai** [comment]
I'm getting `shx` errors from the Windows build pipeline:

```
2019-01-15T16:16:19.1434202Z > shx rm -rf build native\windows\BlockstackBrowser\bin native\windows\BlockstackSetup\bin native\windows\ProtocolHandler\bin native\windows\BlockstackBrowser\Resources\build native\windows\BlockstackBrowser\Resources\cors-proxy native\windows\BlockstackBrowser\Resources\node_modules native\windows\BlockstackBrowser\Resources\node.exe
2019-01-15T16:16:19.1434587Z 
2019-01-15T16:16:19.1476019Z sh: 1: shx: not found
2019-01-15T16:16:19.1503101Z npm ERR! file sh
2019-01-15T16:16:19.1503621Z npm ERR! code ELIFECYCLE
2019-01-15T16:16:19.1503906Z npm ERR! errno ENOENT
2019-01-15T16:16:19.1504200Z npm ERR! syscall spawn
2019-01-15T16:16:19.1514715Z npm ERR! blockstack-browser@0.35.3 win32:clean: `shx rm -rf build native\windows\BlockstackBrowser\bin native\windows\BlockstackSetup\bin native\windows\ProtocolHandler\bin native\windows\BlockstackBrowser\Resources\build native\windows\BlockstackBrowser\Resources\cors-proxy native\windows\BlockstackBrowser\Resources\node_modules native\windows\BlockstackBrowser\Resources\node.exe`
2019-01-15T16:16:19.1515020Z npm ERR! spawn ENOENT
```

**Comment by hstove** [comment]
Do we do code signing of windows builds?

**Comment by zone117x** [comment]
@kantai 
> `2019-01-15T16:16:19.1476019Z sh: 1: shx: not found`

Couple things to note here:

* `shx` is a devDependency that is directly runnable inside package.json scripts. I think this indicates that build machine is on an older version of node/npm where that wasn't possible.
* That output suggests the scripts are being ran inside bash instead of Windows cmd/batch. Which I think indicates that machine has dangerous/breaking deep git-bash integration installed or some other non-typical environment setup, like running everything through the WSL bash, idk. 

Example: 
image

Also this npm build script doesn't do any code signing. 

I recommend leaving the existing codesigned-msi-producing setup alone. Or using a fresh environment/VM that won't cause these issues.

**Comment by zone117x** [comment]
Here's an `appveyor.yaml` for building and producing an msi artifact (not codesigned). Just set it up here https://ci.appveyor.com/project/zone117x/blockstack-browser/build/artifacts

```yaml
image: Visual Studio 2017
environment:
  nodejs_version: 10
install:
- cmd: >-
    powershell -Command "(new-object System.Net.WebClient).DownloadFile('https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311.exe', 'wix311.exe')"

    wix311.exe /install /quiet /norestart

    npm i
build_script:
- cmd: npm run win32
artifacts:
- path: '**\BlockstackSetup.msi'
```

**Comment by kantai** [comment]
This works great for me @zone117x -- tested by using the built artifact to install over existing install.

**Comment by kantai** [comment]
I'm ready to approve this, but why did the `/branch` check failed ?

**Comment by zone117x** [comment]
> I'm ready to approve this, but why did the `/branch` check failed ?

I accidentally removed it from the build queue on AppVeyor's end while testing. If we close then re-open the PR it should work. Want me to try that?

**Comment by kantai** [comment]
Nope -- this is fine.

**Comment by hstove** [comment]
Unfortunately I'm not sure how to review this, since I'm on a Mac. I do have a computer with bootcamp and windows around the house but it's not setup for anything development related. I could spend some time setting up node and trying to build this. But, I trust Aaron's review if it works for him.

**Comment by zone117x** [comment]
@hstove for verifying signature, I think the unix tool [osslsigncode](https://formulae.brew.sh/formula/osslsigncode) that we've been using for signing, can also verify the signature on the msi artifact from appveyor. Not sure about the usage args though. 

> Unfortunately I'm not sure how to review this, since I'm on a Mac.

I use a Windows VM on my Mac. VMWare Fusion and Parallels both work pretty well. But that would take quite some time to setup and install all the requisite tooling. 

I think the fact that the build scripts works on a clean Windows CI (appveyor) is good enough. 

@kantai good to merge?

**Comment by kantai** [comment]
> @kantai good to merge?

Yep, go ahead.

**Pull request merged**
