### PR TITLE
resolved horizontal scroll issue on dash

### PR DESCRIPTION
**Pull request by guylepage3**

### CODE REVIEW

**Comment by shea256** [comment]
@guylepage3 is this pull request still relevant or is it obsolete because of the move to the web version?

**Comment by guylepage3** [comment]
It is not obsolete. we're changing the layout.

**Comment by shea256** [comment]
@guylepage3 Can you elaborate please? Can we close this PR? Or does it need to still be merged in?

**Comment by shea256** [comment]
Thanks @guylepage3. This is obsolete. Closing now.

**Pull request closed without merging**
