### PR TITLE
Feature/consistently order social proofs

### LINKED ISSUE #709: Sort social proof lists in consistent order

### PR DESCRIPTION
**Pull request by craigiansmith**
Provides a consistent alphabetical order for all social proofs. Closes #709.

The AccountTypes constant is defined in two separate places (DefaultProfilePage and EditProfilePage). I have introduced code to sort the social proofs in both files. Going forward it may be possible to apply DRY here, but I have not refactored any code in this PR.

### CODE REVIEW

**Comment by dashaxiong** [comment]
I am still working on this, to make some tests for the DefaultProfilePage in the hope of refactoring it slightly. So, expect more commits :grin:

**Comment by yknl** [comment]
hey @dashaxiong are you still working on this PR?

**Comment by dashaxiong** [comment]
Hi @yknl - yes, I plan to get back to it soon, but first I am setting up some end to end integration tests as per issue #1481.

**Comment by craigiansmith** [comment]
A revised PR has been opened which sorts the social proofs and adds tests #1634

**Pull request closed without merging**
