### PR TITLE
Name registration errors and deny button

### PR DESCRIPTION
**Pull request by aulneau**
### What this does
This PR fixes two main issues:

## Fix id.blockstack name registration https://github.com/blockstack/blockstack-browser/issues/1764
- create id / sign in here -> https://deploy-preview-1898--reporter-beaver-73821.netlify.com
- go to IDs page
- hit 'more'
- generate a new ID
- hit 'add username' 
- search for a free subdomain
- when you are on the page that asks if you'd like to register for free, [**block requests to registrar.blockstack.org**](https://developers.google.com/web/updates/2017/04/devtools-release-notes#block-requests)
- attempt to register the subdomain
- you will see a failure message (this message will not display a support email, however if the server responds with 409, it will show `support@blockstack.org`).
## Reduce misuse of "Deny" button during onboarding https://github.com/blockstack/blockstack-browser/issues/1816
- how to test same tab example:
  - Login / create an account here -> https://deploy-preview-1898--reporter-beaver-73821.netlify.com
  - use this app to sign in https://react-blockstack-redux-bundler-yjnojbyuwr.now.sh/sign-in
  - notice that the 'Cancel' button is in the top right
  - hit the cancel button
- how to test native browser version:
  - clone this repo and checkout this PR `feature/better-errors-notifications`
  - `yarn && yarn dev`
  - set dev mode on the blockstack browser app (opt click icon in nav bar)
  - auth with any blockstack app
  - hit cancel in auth modal
  - window should close

For mobile apps, I've opted to hide the cancel button in general as per @yknl's suggestion.

### CODE REVIEW

**Comment by moxiegirl** [comment]
Went through the process of registering a new ID and then adding a new id as detailed above.

Tiny broken image in the I understand dialog.

image

The new id gets this message that it might take time, but both ids have "processing icons" -- I was under the impression that the first id was successfully registered. Is this not the case?

image

**Comment by aulneau** [comment]
@moxiegirl thank you for going through this!

I think if you had registered your first name within the last few hours, it would be the case that both names would still be processing. Even if you register your initial name through the primary registration/sign up flow, it still takes the same amount of time to process. 

I'm not sure what that broken image is, I will take a look.

**Comment by hstove** [comment]
@aulneau this is done, correct? Just asking because it's still in the `in progress` column.

**Comment by aulneau** [comment]
@hstove should be done, it might not have been moved when i was working on tests! as long as it's approved by you two, should be good to merge :)

**Comment by hstove** [comment]
@timstackblock I'm assigning to you for QA, Thomas has outlined some good testing steps here.

**Comment by timstackblock** [comment]
These both work as expected. I did notice 2 new 404 errors in console when testing #1764 
I have pasted them below with screenshots. It did not seem to affect the registration of the 2nd and 3rd ID but I wanted to bring this to your attention.

 _GET https://core.blockstack.org/v1/names/3rdtesttim.id 404_
_GET https://registrar.blockstack.org/v1/names/3rdtesttim.id.blockstack 404_

Screen Shot 2019-04-25 at 9 42 52 AM
 

Changes to the DENY button work as expected
Screen Shot 2019-04-25 at 9 46 28 AM

**Comment by hstove** [comment]
> I did notice 2 new 404 errors in console when testing #1764. I have pasted them below with screenshots.

Those are fine and expected. This happens when you go to register a new name. It checks the registrar to see if they're already in use - if it returns 404, that means they are available.

**Pull request merged**
