### PR TITLE
Light-weight multi-reader storage

### PR DESCRIPTION
**Pull request by yknl**
Adds ability to add custom key/values to the user profile. This enables a very light-weight form of multi-reader storage. For now custom key/values will need to be manually entered. An update to blockstack.js is planned to give apps the ability to programmatically add/edit key values with the user's permission. Also included in this PR is the ability to delete accounts.

image

Custom account in profile:
image

In edit mode, you can now click on the trash can to delete an account
image

### CODE REVIEW

**Comment by larrysalibra** [comment]
Wow this looks great @yknl! Can’t wait to give it a try! Thanks!

**Comment by guylepage3** [comment]
Very cool @yknl

**Comment by larrysalibra** [comment]
@yknl sorry for taking so long to give feedback on this:

It works pretty well. 
Couple of things:

1. If i click on a custom entry and then try to change it, i end up getting a new one. I'd expect that it lets me edit the value.
2. There doesn't seem to be a way to delete an entry. We could add a delete button in the edit dialog.

Let me know what you think.

**Comment by larrysalibra** [comment]
@yknl If I recall correctly, this was a different implementation of multi-reader storage that let us add custom accounts. Do we want to keep this functionality?

**Comment by vsund** [comment]
This might be not relevant for multi-reader storage anymore, but I'd really like the ability to add custom accounts :)

**Comment by yknl** [comment]
This PR is now obsolete

**Pull request closed without merging**
