### PR TITLE
Search Button Registration: color and margin fix

### PR DESCRIPTION
**Pull request by kkomaz**
Fixes: https://github.com/blockstack/blockstack-browser/issues/802

- Search Button margin and color fix.
- Previously the button was white.

Old:
screenshot of google chrome 9-20-17 9-19-40 pm

New:
screenshot of google chrome 9-20-17 9-00-15 pm

### CODE REVIEW

**Review by larrysalibra — APPROVED** [review]

**Comment by larrysalibra** [comment]
Thanks for this @kkomaz !!

**Comment by guylepage3** [comment]
hey @kkomaz @larrysalibra , noticed that the "cancel" button is not adhering to our defined design style and should apply `btn-block` to that button.

**Comment by guylepage3** [comment]
@kkomaz i'm going to create a new issue for the above if you'd like to execute another pull request for it?

**Comment by kkomaz** [comment]
So I took a look at adding the `btn-block` on the cancel button but it looked odd to me.  

screenshot of google chrome 9-21-17 9-13-17 am

Your call @guylepage3  if you're okay with it 👍

**Comment by guylepage3** [comment]
Hey @kkomaz Let' make both buttons `btn-primary` `btn-block` and place them both in the same div so they are consistent.

**Comment by kkomaz** [comment]
@guylepage3 Ok I can take a look into wrapping it in the same div.  To confirm your ask..... you want the "cancel" button to also be blue?  Don't you think that would be confusing to the user?  Also let me know what the issue ticket is and I'll create a new PR 😄

**Comment by kkomaz** [comment]
@guylepage3 which branch should i be comparing to?

**Pull request merged**
