### PR TITLE
Verify app origin and display app origin to user

### PR DESCRIPTION
**Pull request by larrysalibra**
I've updated the authentication dialog to use a new drop in replacement for `loadAppManifest` called `verifyAuthRequestAndLoadAppManifest` that checks that the authentication request is valid before loading the app manifest. This pull request depends on this blockstack.js: https://github.com/blockstack/blockstack.js/pull/340 

The blockstack.js version used in this branch will have to be updated once the above pull request is merged and shipped to npm.

Includes a quick and dirty update to the authentication screen to show the claimed app origin that has been used in verifying the auth request:

screen shot 2018-01-08 at 9 47 51 pm

This addresses issue https://github.com/blockstack/blockstack-browser/issues/1147

### CODE REVIEW

**Comment by kantai** [comment]
This works for me -- however, this modal looks kind of bad when the app domain is long:

sign-in-with-app-domain

Could set the appdomain on it's own line, bold it, or something along those lines.

**Comment by larrysalibra** [comment]
@kantai great feedback! - will make some changes and push a new commit

**Comment by larrysalibra** [comment]
@kantai Thank you for the feedback. 

I updated this pull request to display the app origin on a new line:

screen shot 2018-01-22 at 7 12 00 pm

**Comment by larrysalibra** [comment]
Thanks for taking a look at this @kantai - it's now merged!

**Pull request merged**
