### PR TITLE
Add Cypress.io for running end-to-end integration tests

### PR DESCRIPTION
**Pull request by craigiansmith**
Addresses #1575, and #1481

**This PR adds Cypress as a dependency and creates an initial test suite for the sign up workflow.**

To install it:  `npm install`

Then on Ubuntu, you will also need to install libgconf-2.4, which is an outdated dependency which throws Glib-GIO-CRITICAL warnings as mentioned in this [issue](https://github.com/cypress-io/cypress/issues/1526). Install it with: `sudo apt install libgconf-2-4`.

The integration test is located at _test/cypress/integration_, though this can be configured differently. Out-of-the-box it uses a _cypress_ directory in the root of the project. Occassionally, cypress creates that folder, even though new locations have been specified in _cypress.json_.

To prepare the test environment:
`npm run dev`

Then when the server is built:
`npx cypress open`

This will launch a new window, click: `run all specs` and it will start running through the tests.

To run the tests headless, use `npx cypress run`.

What do you think :question: 
     
@aulneau @yknl @wbobeirne

### CODE REVIEW

**Comment by craigiansmith** [comment]
The extra cypress folder is no longer created. There was a typo in the config file, which is now fixed.

**Comment by yknl** [comment]
Hey @craigiansmith, we've start implementing end-to-end tests using selenium-webdriver on BrowserStack. We evaluated cypress.io but found that it doesn't suit our needs. Our goal with automated end-to-end tests was to test basic functionality across multiple browsers/platforms. Cypress.io doesn't have support for anything other than chrome-like browsers.

**Comment by aulneau** [comment]
Thanks for your work on this @craigiansmith 

I would perhaps reconsider using this @yknl, related -> https://www.cypress.io/blog/2018/09/20/cypress-is-officially-out-of-beta/

Coming soon:
> Cross browser support with native events, Sauce Labs, and even IE11.

I've heard a lot of the internet really praise cypress (I don't have any personal experience with it).

**Comment by yknl** [comment]
I think we can reconsider cypress once their cross browser support is released. And if mobile browsers are also supported.

**Comment by yknl** [comment]
Closing this for now as there's no cross browser support in cypress right now.

**Pull request closed without merging**
