### PR TITLE
Onboarding Bug Fixes

### LINKED ISSUE #1452: Blockstack Browser does not set usernames after user recovers their ID's
- Operating system and version: Mac OS X
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Blockstack version: 0.29.1
- How you installed Blockstack: yes
- Steps to reproduce: see attached video

[blockstack_browser_recovery_bug.zip](https://github.com/blockstack/blockstack-browser/files/2077125/blockstack_browser_recovery_bug.zip)

### LINKED ISSUE #1460: Email scope no longer working after latest update
The email scope in auth is no longer working as reported by some developers.

### LINKED ISSUE #1463: Message is confusing. Possibly remove
Screen Shot 2018-06-18 at 8:08 PM

https://forum.blockstack.org/t/recover-password/5498/1

Consider moving to the second step, where the password is needed. There is already language there. 

---
### More Info

**Source URL**: [https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-in](https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-in)

### PR DESCRIPTION
**Pull request by aulneau**
This PR addresses many of the bugs that have been reported by users since we've launched the new onboarding experience.

- Removes redundant text on restore screen, resolves #1463
- Identity/profile loading bugs: resolves #1452, #1431, #1355
- Adds email into the restore flow, resolves #1460 
- Adds email checkbox for newsletter subscription
- Ensures lower case when registering a name
- Updates the arrangement of words on the seed view screen. will update in a different PR

### CODE REVIEW

**Comment by yknl** [comment]
Thanks for the fixes @aulneau, I'm going to block of time tomorrow to review this!

**Comment by jeffdomke** [comment]
screen shot 2018-06-27 at 4 59 12 pm

Failing when trying to restore a ID I just created with seed.

**Comment by yknl** [comment]
I just tried restoring a seed that I just created and did not encounter that error. @jeffdomke can you provide more details on the steps you took?

**Comment by jeffdomke** [comment]
Annoying. Just tried to recreate and could not. The first time I cleared my local storage and tried a second time and could reproduce. Now I can't. Remembering from before, I created an ID, copied the seed, reset the browser, recovered with seed, then used a different password, then hit that failure state. 

Probably safe to ignore unless one of us can recreate.

**Pull request merged**
