### PR TITLE
Support for ctrl+click "Enable development mode" in Windows app

### PR DESCRIPTION
**Pull request by zone117x**
Needed this for debugging auth problems with Edge (see note https://github.com/blockstack/blockstack-browser/pull/1793#issuecomment-454417234)

Ported over the handy `ctrl+click tray icon` -> `enable development mode` -> `npm run dev` feature we have on macOS. 

This also slightly improves the bug where:
1. User installs blockstack.msi
2. The Blockstack native process is not automatically started after install (this should be fixed in another PR).
3. User clicks "login with blockstack" on web app. 
4. The native protocol handler launches the user's web browser to `http://localhost:8888` which fails to load since the main native application is not running. 
5. User has no idea whats going on. 

This PR now shows a message box notifying the user that the Blockstack application is not running.

Future PR should have the installer start the app once done, and register an auto-start on system reboot.

### CODE REVIEW

**Comment by markmhx** [comment]
@zone117x Has this issue's solution been completely reviewed and as such can be closed in anticipation of release? If not, who'd be best suited to review?

**Comment by zone117x** [comment]
I don't think this has been reviewed yet. I think @kantai is best person to look over the C#, and @hstove is next best reviewer since he can test it out on Windows. 

Also note that this PR has some really similar changes that I would make to address https://github.com/blockstack/blockstack-browser/issues/1167
Perhaps we can save some review/QA resources by having 1 PR for both of these?

**Comment by hstove** [comment]
I haven't been able to fully setup my Windows dev environment still. Is there a link to a packaged app that I can test? Or can you upload one?

**Comment by kantai** [comment]
The source changes look good to me, I will test that it runs correctly on my windows device now.

**Comment by kantai** [comment]
> I haven't been able to fully setup my Windows dev environment still. Is there a link to a packaged app that I can test? Or can you upload one?

You can get automated windows build artifacts from PRs now:

https://ci.appveyor.com/project/Blockstack/blockstack-browser/builds/21944832/artifacts

**Comment by hstove** [comment]
> You can get automated windows build artifacts from PRs now:

Awesome. So even though we don't get build checks for non-master commits, AppVeyor will still do they builds?

**Comment by zone117x** [comment]
@hstove We should port your MacOS debug w/ hosted browser URL feature into here. 
The native swift/C# is just for the tray icon menu item right?

**Comment by kantai** [comment]
> @hstove We should port your MacOS debug w/ hosted browser URL feature into here.
> The native swift/C# is just for the tray icon menu item right?

Let me know once that's updated here-- I'll hold off on testing this until then.

**Comment by hstove** [comment]
Yeah, the Swift code is for the tray icon, and also for determining which URL to redirect to from the protocol handler.

Once I build the actual page that redirects you to the beta URL with your encrypted seed, you'll be able to use that in the Windows version.

**Comment by markmhx** [comment]
@hstove is going to review this soon even if the beta mode work isn't done, and @kantai I think this is ready for your review as well

**Pull request merged**
