### PR TITLE
/sign-out path and misc ui updates

### PR DESCRIPTION
**Pull request by aulneau**
### What this does

This fixes a few issues:
- #1624 (square aspect ratio of avatars)
    - https://github.com/blockstack/blockstack-browser/pull/1859/commits/9b871f7b7b379d4cae5a3e6f33f37b4595f7cc14
- #1799 (`/clear-auth` -> `/sign-out`) 
    - https://github.com/blockstack/blockstack-browser/pull/1859/commits/00520f9b8851394c1543424ddf5da9d79c1aeb7a
- Refactored nav bar to use `mdi-react`

screen shot 2019-03-06 at 3 04 44 pm

screen shot 2019-03-06 at 2 58 15 pm

### CODE REVIEW

**Comment by markmhx** [comment]
@aulneau Is the above unit test something you can fix soon so we can get this merged?

**Comment by aulneau** [comment]
> @aulneau Is the above unit test something you can fix soon so we can get this merged?
I reached out to the group a couple weeks ago and most people agreed that many of these unit tests aren't really useful/are legacy and we don't need them. I will check in with @timstackblock and get back to you.

**Comment by timstackblock** [comment]
> > @aulneau Is the above unit test something you can fix soon so we can get this merged?
> 
> I reached out to the group a couple weeks ago and most people agreed that many of these unit tests aren't really useful/are legacy and we don't need them. I will check in with @timstackblock and get back to you.

I have worked with the e2e test I think that these are valuable and should NOT be deleted. They have some flakes and should be refactored. There is an open issue for this and I am looking into it. 

As for unit test, my experience is that these are just developer test, and their primary purpose is to verify small components of the code during development. If the code is being refactored usually the developers would refactor the unit test at same time. 

I would defer to the developer who created them, they don't really test end to end, its possible for the unit test to pass and the QA engineer's e2e test to still fail because of integration issues so they are for development purposes.

**Comment by aulneau** [comment]
Will resolve conflicts and try to get tests passing this week.

**Comment by timstackblock** [comment]
Tested this still one small issue circle avatars

**Comment by markmhx** [comment]
We've decided to address https://github.com/blockstack/blockstack-browser/issues/1624 in a separate PR.

**Pull request merged**
