### PR TITLE
[WIP] New user onboarding

### PR DESCRIPTION
**Pull request by aulneau**
https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-up
https://deploy-preview-1268--reporter-beaver-73821.netlify.com/seed
https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-in

### CODE REVIEW

**Comment by larrysalibra** [comment]
Awesome job on this! Trying to set up a staging server for this to test with mobile SDKs and tests are failing because of the lint. Is it possible to clean it up?

**Comment by aulneau** [comment]
@larrysalibra sure thing, just pushed should be good to for lint tests!

**Comment by aulneau** [comment]
ooo I see flow tests are broken too due to module aliasing, I'll fix that and push up shortly

**Comment by aulneau** [comment]
okay @larrysalibra tests pass

**Comment by yknl** [comment]
This has been tested and reviewed by @jeffdomke @larrysalibra @jcnelson

**Pull request merged**
