### PR TITLE
Adds warnings while registration pending

### PR DESCRIPTION
**Pull request by kantai**
Adds a warning message to transaction sending views when a registration is pending. This partially addresses issue #1240 by warning users that withdrawing bitcoin or trying to submit another registration while their other registration is pending risks interfering with their other registration.

We can remove these warnings once the browser is smart enough to adjust a user's UTXO set or display more information about pending operations.

## Testing

You can test this in mainnet by submitting a registration, and then trying to submit another one, or view the bitcoin spend page.

You can test this in regtest by firing up the docker regtest container:

```
IMAGE=$(docker run -dt -p 6270:6270 -p 16269:16269 -p 18332:18332 -e BLOCKSTACK_TEST_CLIENT_RPC_PORT=6270 -e
 BLOCKSTACK_TEST_CLIENT_BIND=0.0.0.0 -e BLOCKSTACK_TEST_BITCOIND_ALLOWIP=172.17.0.0/16 quay.io/blockstack/integrationtests:mas
ter blockstack-test-scenario --interactive 2 blockstack_integration_tests.scenarios.browser_env)
```

Running the browser:

```
npm run dev-proxy & npm run dev
```

And opening: `http://localhost:3000/#coreAPIPassword=blockstack_integration_test_api_password&regtest=1`

Then you can submit a registration (after loading up your wallet with `core-send`) and check out the warnings.

Screenshots:

warn-register
withdraw

### CODE REVIEW

**Comment by larrysalibra** [comment]
taking a look at this now!

**Comment by kantai** [comment]
I agree that we should not allow users to submit these operations, but only if we _really_ know that they will break a registration. Currently, this just iterates to see if there are any 'pending' names (as denoted by the redux state). Unfortunately, that's not always truthful, because a registration that fails will remain pending forever. That's a problem that should also be solved, but will require a lot more intelligence on the client (tracking the sent transactions, seeing if they are in the mempool, how long has it been since the preorder confirmed?)

In the case we deal with now, the browser doesn't know _for sure_ that a registration will break if the user submits a registration or bitcoin spend, hence, just a warning.

**Comment by larrysalibra** [comment]
@kantai that makes sense to me. Changing my review to approve.

**Comment by kantai** [comment]
Thanks @larrysalibra -- merging now.

**Pull request merged**
