### PR TITLE
Add Graphite app to the browser home page.

### PR DESCRIPTION
**Pull request by jehunter5811**

### CODE REVIEW

**Comment by jehunter5811** [comment]
@yknl Sorry about that! Made the change.

**Comment by yknl** [comment]
Thanks!

**Comment by jehunter5811** [comment]
@yknl any idea why the icon would be broken? Seems like I had both sizes included in the commit and titled properly...

**Comment by yknl** [comment]
@jehunter5811 are you experiencing the same thing as @dantrevino on v0.22.0? What operating system are you using?

**Comment by jehunter5811** [comment]
@yknl I just downloaded it and it works for me on Mac. Looks great! Thanks!

**Comment by kantai** [comment]
I'm also experiencing this issue --

it looks like the file `app-icon-graphite-256X256.png` should be `app-icon-graphite-256x256.png`

https://github.com/blockstack/blockstack-browser/blob/master/app/images/app-icon-graphite-256X256.png

Maybe the difference on OS's comes down to macOS case-insensitivity ?

**Comment by jehunter5811** [comment]
Good catch. I just tried to commit a new branch and open a pull request, but it didn't look like anything was committed. All I changed was the "X" to "x" so maybe git didn't recognize that as a change?

**Comment by kantai** [comment]
I opened a PR for the name change @jehunter5811 -- we should be able to do another point release to get this working on other OSes.

**Pull request merged**
