### PR TITLE
Authenticate with the users configured gaia hub

### PR DESCRIPTION
**Pull request by kantai**
This addresses issue #1490 --

This uses the user's configured gaia hub: `settings.api.gaiaHubUrl` to set the app-specific URL and the `hubURL` field of the authentication response object.

This will allow a user who has  configured a gaia hub to use it to sign into applications (multi-player and single-player). _However_ this will not address migrating data from one hub to another -- if a user changes their gaia hub URL, they will appear to have a blank slate of data at the app-specific bucket.

### CODE REVIEW

**Comment by aulneau** [comment]
@kantai is there a way to test that this works -- is there a different gaia hub url I can swap in without spinning up my own?

**Comment by kantai** [comment]
Try this one:

`https://gaia-aaron-hub.herokuapp.com/`

**Comment by jcnelson** [comment]
> This will allow a user who has configured a gaia hub to use it to sign into applications (multi-player and single-player). However this will not address migrating data from one hub to another -- if a user changes their gaia hub URL, they will appear to have a blank slate of data at the app-specific bucket.

This will also break multiplayer storage, since data written to the new Gaia hub will not be visible.  As is, this could lead to data loss and data corruption.

**Comment by kantai** [comment]
> This will also break multiplayer storage, since data written to the new Gaia hub will not be visible.

No -- it will update the app key entry in the profile. Multi-player storage will continue to work.

>  As is, this could lead to data loss and data corruption.

The data is not migrated, so it will look to the user like a new login. However, it shouldn't lead to data corruption or data loss.

**Comment by jcnelson** [comment]
@kantai I tested this patch.  I changed my Gaia hub API endpoint in the API settings page of the Browser, but when I signed into an app with it, the read URL was *not* changed in my profile.  I used an HTTP Gaia hub (not available via HTTPS)--maybe that interfered with updating my profile?

**Comment by kantai** [comment]
@jcnelson -- I think what's going on is that the browser can't write the profile anymore once the hubUrl config changes. This patch ultimately only addresses (https://github.com/blockstack/blockstack-browser/issues/1244) -- the browser itself will have to be much more sophisticated about how hubs are configured before it will support changing the hubUrl after a name is already registered.

**Comment by jcnelson** [comment]
Okay, then I think I misunderstood above.  You're saying that the Gaia hub URL in the API settings page *after I create a name* will **not** change the Gaia hub for the application I sign into (neither the read nor write paths will be affected), right?

**Comment by kantai** [comment]
Changing the gaia hub url in the settings page after you've registered an ID will make the browser unable to update your profile at all.

**Comment by jcnelson** [comment]
> Changing the gaia hub url in the settings page after you've registered an ID will make the browser unable to update your profile at all.

It sounds like we need a settings item for both the profile Gaia hub and an application data Gaia hub.

**Pull request merged**
