### PR TITLE
Fixing flexbox orientation

### PR DESCRIPTION
**Pull request by matheusml**
#320

### CODE REVIEW

**Comment by guylepage3** [comment]
@matheusml can you please pull from `ui-0.11` branch and I'll merge it in?

**Comment by matheusml** [comment]
Done!

**Comment by larrysalibra** [comment]
Thanks @matheusml !
@guylepage3 you take a look at this and merge it into your design branch if appropriate?

**Comment by guylepage3** [comment]
@larrysalibra @matheusml taking a look at this now

**Comment by guylepage3** [comment]
Ok. so we're actually looking to execute something a bit different here @matheusml. If you see below, you've adjusted `flex-box`'s justification to be `flex-start` which does align objects left to right and flow down. but what we are looking to execute is to center objects and have them flow outward.

Would you like to take another stab at it? 😄 

screenshot 2017-07-07 11 35 17

**Pull request merged**
