### PR TITLE
Support for new protocol detection technique

### PR DESCRIPTION
**Pull request by zone117x**
Creating PR only to get a build from netlify.

### CODE REVIEW

**Comment by hstove** [comment]
(Posting here so I remember)

URL to test the auth flow: https://zone117x.github.io/blockstack-protocol-ping-demo/public/

**Comment by kantai** [comment]
@zone117x -- how would you recommend testing this? Does the following seem right?

1. Ensuring that the auth flow works normally for current applications.
   a. Creating new account
   b. With existing account
2. Ensuring that the auth flow works normally for the test app built with the prototype protocol detection.

Does that seem right?

**Comment by zone117x** [comment]
@kantai Yes, I think both those tests should validate backwards compatibility.

**Comment by jeffdomke** [comment]
Tested only in Chrome and Safari. Amazing. 👏👏👏

Safari: I'm noticing that when I have the browser installed, and click "open" it will open the local browser in Chrome (since it is default). Ideally, the behavior would be: Open an app in Chrome = open local browser in Chrome. Assume this is expected behavior but it caught my attention. 

Safari: Notice the little weird scrolling jumpiness.

Those are tiny issues, think we should ship even if they can't be fixed. Well done @zone117x

**Comment by zone117x** [comment]
> Ideally, the behavior would be: Open an app in Chrome = open local browser in Chrome. 

This issue is pre-existing and being tracked here: https://github.com/blockstack/blockstack-browser/issues/1759#issuecomment-451953973

**Comment by zone117x** [comment]
@hstove This PR currently does not perform the redirect ping if the local browser has no account logged in. Which causes the web app in the original tab to redirect to the hosted browser. 

This appears to be the area that would need modified https://github.com/blockstack/blockstack-browser/blob/3cfb20426ea52997a88f978b78e35786d54683d7/app/js/routes.js#L225
I'm not familiar with React and adding the redirection code here seems like a more risky change that would require additional review. 
Any idea of a quick and safe way to do fix this?

**Comment by hstove** [comment]
> @hstove This PR currently does not perform the redirect ping if the local browser has no account logged in. Which causes the web app in the original tab to redirect to the hosted browser.

Fixed!

**Comment by zone117x** [comment]
> > @hstove This PR currently does not perform the redirect ping if the local browser has no account logged in. Which causes the web app in the original tab to redirect to the hosted browser.
> 
> Fixed!

That was fast 👍

**Pull request merged**
