### PR TITLE
#1205 Upgrade to React 16

### PR DESCRIPTION
**Pull request by cwackerfuss**
Addresses ticket #1205 

Changes required to upgrade to React 16:

- Updated versions on `react`, `react-dom`, and `react-modal`
- PropTypes has been moved out of React core into a standalone module
- The `react-radio-group` module does not support React 16, and a [simple PR](https://github.com/chenglou/react-radio-group/pull/45) opened by a community member in November 2017 is yet to be merged, which tells me this module is unmaintained. But that's okay since the only place we used this module actually didn't require or use it's functionality.

To test:
This ticket should require a full regression test to make sure no edge case functionality depends on non-Fiber-friendly code. I did as much initial testing as I could but this could use some more eyes.

### CODE REVIEW

**Comment by larrysalibra** [comment]
Thanks for this pull request @cwackerfuss ! taking a look at this now.

**Comment by larrysalibra** [comment]
After @yknl has a chance to take a look, if he doesn't see any problems, please go ahead and merge this to develop!

**Comment by cwackerfuss** [comment]
Sweet, thanks @larrysalibra!!

**Comment by yknl** [comment]
Thanks @cwackerfuss, looks great! Just one thing, I think the upgrade to the new version of `react-modal` is causing the warning below to appear whenever you open a modal. 

image

**Comment by cwackerfuss** [comment]
Oh great catch @yknl, fixing this now

**Pull request merged**
