### PR TITLE
Allow reset on update page

### PR DESCRIPTION
**Pull request by aulneau**
### What this does

Whenever we update or change the structure of the application state object, we will increment the state version constant, forcing the end user to enter their password so we can restore their account after wiping everything. A common problem users have been running into is that there might be multiple passwords, or a user might just forget their password. Currently there is no easy way to reset the browser from this view. 

This PR adds the option to reset the browser from this screen, and then redirects the user to the sign in view.

I've also updated some of the dependencies in this project.

This resolves https://github.com/blockstack/blockstack-browser/issues/1760

### To do:
- [x] Ensure app auth requests persist through clearing of local data

screen shot 2019-01-23 at 10 35 06 am
screen shot 2019-01-23 at 10 34 57 am

### CODE REVIEW

**Comment by aulneau** [comment]
Perfect, thank you @markmhx.

I don't think it makes sense to link `register a new Blockstack ID`, because the user still needs to do the act of resetting before being able to `sign-up`. I'll change the rest of it though!

**Comment by aulneau** [comment]
screen shot 2019-01-23 at 1 40 58 pm

I changed 'remember' to 'have' in this sentence: `If you don't remember your Secret Recovery Key,` as I think it's more typical that people would store their key, and not ever need to 'remember' it.

I'm not sure what the button should say other than `reset` or `continue`. what do you think @markmhx?

**Comment by markmhx** [comment]
@aulneau Looks good, maybe "Continue" best to keep it neutral and on the path to "sign in"?

**Comment by aulneau** [comment]
@markmhx @hstove @zone117x Thanks for your reviews and feedback! I have merged the changes in :)

**Comment by markmhx** [comment]
@aulneau Thanks for jumping on this! Excited to get it out.

**Pull request merged**
