### PR TITLE
v0.37.0

### PR DESCRIPTION
**Pull request by hstove**
This is a release branch for version 0.37.0. We'll keep it as a PR during the beta period, until we merge this into master. All QA for this release should be done from this branch.

Changes:

- [#1966](https://github.com/blockstack/blockstack-browser/pull/1966): w3c crypto, greatly improving cryptographic performance. Updates blockstack.js to v21.0.0-alpha.4. Also includes lots of code health improvements
- [#1965](https://github.com/blockstack/blockstack-browser/pull/1965): Adding a notice to the wallet page
- [#1973](https://github.com/blockstack/blockstack-browser/pull/1973): Allowing collection scopes during auth
- [#1971](https://github.com/blockstack/blockstack-browser/pull/1971): Open app after installing on Windows
- [#1951](https://github.com/blockstack/blockstack-browser/pull/1951): Update MacOS native code to Swift 4
- [#1942](https://github.com/blockstack/blockstack-browser/pull/1942): Update blockstack.js to v19
- [#1938](https://github.com/blockstack/blockstack-browser/pull/1938): Allow renewing Blockstack IDs
- Removes all social proofs except for Twitter

### CODE REVIEW

**Comment by moxiegirl** [comment]
@LGTM

**Comment by hstove** [comment]
**Important**: Alex Lee reported that the 'renew' button isn't showing up for him, with a name that is already expired.

**Comment by markmhx** [comment]
I believe we want to omit the gear icon that leads to the "Update zone file" and "Transfer name" pages per https://github.com/blockstack/blockstack-browser/pull/1938#issuecomment-552988257.

Screen Shot 2019-12-03 at 16 09 54
Screen Shot 2019-12-03 at 16 09 56

**Comment by markmhx** [comment]
I'm getting this error when trying to renew my ID:

Screen Shot 2019-12-03 at 16 13 23

**Comment by hstove** [comment]
@markmhx , that's interesting, what browser are you using? And hosted vs. native? I have not seen that error, but it may have come up from the merge with Matt's crypto PR.

**Comment by zone117x** [comment]
Was able to reproduce the renewal error. Fixed in PR https://github.com/blockstack/blockstack-browser/pull/1998

**Comment by hstove** [comment]
> I believe we want to omit the gear icon that leads to the "Update zone file" and "Transfer name"

:+1: removed

**Comment by markmhx** [comment]
Let's add these two issues to this release for removing all social verifications except for Twitter and improving the URL included in the tweet for Twitter: https://github.com/blockstack/blockstack-browser/issues/2003 and https://github.com/blockstack/blockstack-browser/issues/2004

**Comment by timstackblock** [comment]
@hstove Social proof changes work well. There is still one small bug for renewals I created here https://github.com/blockstack/blockstack-browser/issues/2016. Once this is done we should be good to go.

**Pull request merged**
