### PR TITLE
Change Sign In Button Copy

### LINKED ISSUE #1601: Restore copy change
Screen Shot 2018-08-10 at 6:57 PM
---
### More Info

**Source URL**: [https://browser.blockstack.org/sign-up?redirect=%2F%23coreAPIPassword%3DPretendPasswordAPI%26logServerPort%3D](https://browser.blockstack.org/sign-up?redirect=%2F%23coreAPIPassword%3DPretendPasswordAPI%26logServerPort%3D)

### PR DESCRIPTION
**Pull request by wbobeirne**
Closes #1601.

screen shot 2018-08-13 at 12 45 09 pm

### CODE REVIEW

**Comment by aulneau** [comment]
I'm not sure we need 'existing' to be capitalized?

**Comment by wbobeirne** [comment]
Just went with the formatting here, but happy to change it https://github.com/blockstack/blockstack-browser/issues/1601#issuecomment-412526231

**Comment by jeffdomke** [comment]
I'm not sure why I did that. No special reason, just typing fast. Sure, de-capitalize it.

**Comment by yknl** [comment]
It would make sense to also rename the next page to "Sign in with your Blockstack ID" and "Sign In" instead of "Restore". What do you guys think?
image
image

**Comment by jeffdomke** [comment]
Agreed, although I think it should read: "Sign in with existing an ID"

**Pull request merged**
