### PR TITLE
Chore/upgrade test & coverage + test account store

### PR DESCRIPTION
**Pull request by narbo**
* Upgraded coverage framework to use nyc instead of legacy istanbul
* Removed deprecated gulp-jsx-coverage
* Moved tests/* to test/* - to be able to use mocha native/default behaviour
* Updated README accordingly
* added babel-plugin-rewire for clean, decoupled testing
* wrote tests for all of account/store/account/actions   
* wrote tests for all of account/store/account/reducer   

( contribute.blockstack.org - nico.id )
NB: Due to the change from istanbul 1.0 to 2.0,  the resulting pct of coverage are not comparable to the original branch.
But the tests written in this PR do increase the branch coverage by more 5% and the impact over all coverage metrics is significant. In order to check this result with comparable numbers, you can simply try running `npm run test` after the 2 first commits but before the last 2 commits of this PR and then re-run them with the whole PR (4 commits).

### CODE REVIEW

**Comment by aulneau** [comment]
Awesome! thanks for this, I was playing around with this the other day and you've already done it! Will review today.

**Comment by narbo** [comment]
@aulneau I did not manage to reproduce the failing test (all tests were passing locally for me) but I did spot a few setTimeouts that were still lying here and there in the tests. I removed those (as they should not be needed). Please let me know if you're still seeing something weird

**Comment by narbo** [comment]
@aulneau I've also just rebased the branch on develop fyi

**Comment by aulneau** [comment]
Wonderful, approved!

**Comment by narbo** [comment]
thanks @aulneau

**Comment by aulneau** [comment]
Thank you for your PR and work on the testing, really appreciate it!!

**Comment by narbo** [comment]
@aulneau I am sorry to bother you with this but could you please check why my contribution on contribute.blockstack.org with id: nico.id and linking to this PR was not accepted? Thank you so much.

**Comment by aulneau** [comment]
@narbo no worries! contribute.blockstack.org is something different than contributors on github projects. You are listed here -> https://github.com/blockstack/blockstack-browser/graphs/contributors as a contributor! I believe contribute.blockstack.org is for tasks unrelated to coding.

**Pull request merged**
