### PR TITLE
Fix Search Button styles and refactor button vs. link logic

### PR DESCRIPTION
**Pull request by kkomaz**
Fixes: https://github.com/blockstack/blockstack-browser/issues/802

1. Per discussion with @guylepage3, I moved the cancel button inside of each component that utilizes the cancel button
2. Made the components into class components.

@yknl I noticed we use the `react-router` `<Link />` component but style them with `btn btn-primary btn-block`.  I think if the purpose of the component is to be a **button** we should wrap it with a `button` element and style them appropriately with the classNames.  To fix the issue of navigating away we can use the `browserHistory` functionality and push those routes `onClick` as needed.  What do you think?

demo

### CODE REVIEW

**Comment by guylepage3** [comment]
this is awesome @kkomaz!!!! 😄

**Comment by guylepage3** [comment]
@kkomaz I see what you're suggesting with `browserHistory` but we should keep consistent for now with the React Router `<Link />` component.

Can you make that change?

**Comment by kkomaz** [comment]
@guylepage3 

One of the issues I noticed with using `<Link>` is that the CSS doesn't play well with it.

`btn-block` spacing only applies if 

1. They are both buttons.
2. They are siblings.

screenshot of screenfloat 9-21-17 6-58-40 pm


Unfortunately one is a `Link` and the other is a `button` 😞   What do you think?

**Comment by kkomaz** [comment]
I'll revert it back and see if I can make that spacing in CSS

**Comment by kkomaz** [comment]
There was no css changes needed.  I just needed the links to be siblings. 

screenshot of google chrome 9-21-17 9-32-35 pm

screenshot of google chrome 9-21-17 9-32-58 pm

**Comment by larrysalibra** [comment]
Looks good to to me! Thanks @kkomaz!

**Comment by guylepage3** [comment]
@kkomaz there is probably the `form-group` or `form-control` container on the first modal. simply apply a container to the other modal windows to match the width of the `form-group`/`form-control`.

**Pull request merged**
