### PR TITLE
Docs site changes

### PR DESCRIPTION
**Pull request by moxiegirl**
Renaming the current docs directory to maintainers --- it appears to be all internal material.
Moving user facing material about the browser into the docs directory.
- what is an id
- install the browser

This closes:
- https://github.com/blockstack/blockstack/issues/433
-  #1466 
-  #886

### CODE REVIEW

**Comment by moxiegirl** [comment]
@yknl could you review this please? Also, I am going to need merge on this repo at some point. I typically don't merge unless there is a pure `doc` only merge.

**Comment by moxiegirl** [comment]
@yknl this needs to land in `master` for my automation scripts.  Can you explain to me your branching strategy a bit, that way I can understand why the move?

**Comment by yknl** [comment]
hey @moxiegirl, the `master` branch always matches what's in the latest shipped release. We open pull requests to `develop` and merge to the `master` branch when we make a release. The changes will eventually make it to `master` so it shouldn't break your automation.

For reference: https://github.com/blockstack/blockstack/tree/master/engineering#repository-management

**Comment by moxiegirl** [comment]
Thanks @yknl merged as agreed in the meeting. Future PRs against develop.

**Pull request merged**
