### PR TITLE
Design update to profile view

### PR DESCRIPTION
**Pull request by yknl**
#569

### CODE REVIEW

**Comment by guylepage3** [comment]
@yknl can you screen shot your new layout for me? 😄

**Comment by yknl** [comment]
profile

**Comment by guylepage3** [comment]
Awesome @yknl 😄 I'll pull this in in the am. thank you sir. :)

**Comment by larrysalibra** [comment]
Thanks @yknl for the pull request!

**Comment by larrysalibra** [comment]
@yknl were you implementing the design from #569 ?

On my computer, some items are misalign:

* The list of accounts: the green verified check causes the account to no longer be aligned with the unverified accounts above or below
* The profile area is also not aligned with the search bar
* The button on the bottom left is sort of just floating out there and seems to still be the old color.

This is how it looks for me:

screen shot 2017-07-20 at 6 09 19 pm


This is the intended design:

27608721-7e6324fa-5b56-11e7-8c76-2e17f80d9f31

Is this a work in progress?

**Comment by yknl** [comment]
@larrysalibra fixed

profile-design-update-fix

**Comment by larrysalibra** [comment]
Thank you @yknl - looks great now!

**Pull request merged**
